### PR TITLE
refactor!: game versioned missionsInLocation, fix certain contracts when resolved, rename missionsInLocations -> missionsInLocation

### LINKED ISSUE #510: Satanta (Jeffery) escalation not loadable in h7
**Describe the bug**
Error starting contract. Maybe because of the `constantjeff` brick added in H3 contract creation.

**To reproduce**
Start the escalation in H2

**Additional context**
image

### PR DESCRIPTION
**Pull request by AnthonyFuller**
Fixes #510 #505 #504

Needs testing and checking over more than twice.

## Breaking Changes
- `controller.missionsInLocations` is now `controller.missionsInLocation` (as it always should have been!).
- The aforementioned `controller.missionsInLocations` is now **split by game version**.
- `controller.addEscalation` has a new parameter: `(groupContract, locationId, **gameVersion**, ...levels)` (highlighted using asterisks).

---

Also this removes some terrible hacks we've had to do. We should've always done it like this!

### CODE REVIEW

**Comment by AnthonyFuller** [comment]
Discussion question before it should be considered to be merged: should `controller.addEscalation` even add it to `missionsInLocation` or should that be up to the plugin? (`scanForGroups` may need to be made public if we leave it up to the plugin)

File: components/controller.ts [hunk 1]
```diff
@@ -626,6 +626,47 @@ export class Controller {
...
+     *
+     * An example of this is the location for Holiday Hoarders changing in
+     * HITMAN 3 thus breaking the contract in standalone 2016.
+     *
+     * @param contract The contract to fix.
+     * @param gameVersion The game version.
+     * @returns The fixed contract.
+     * @private
+     */
+    private fixContract(
```
Comment (RDIL) [inline components/controller.ts:640]: Let's add a hook here in case plugins need to run their own transforms

File: components/menus/destinations.ts [hunk 2]
```diff
@@ -420,13 +418,18 @@ export function getDestination(
         (subLocation) => subLocation.Properties.ParentLocation === LOCATION,
     )
 
-    if (query.difficulty === "pro1") {
-        type Cast = keyof typeof controller.missionsInLocations.pro1
+    // I know it's redundant to check game version here, but it's just for typescript.
+    if (query.difficulty === "pro1" && gameVersion === "h1") {
```
Comment (RDIL) [inline components/menus/destinations.ts:422]: For safety lets do an assertion and remove the gameVersion check

**Review by RDIL — CHANGES_REQUESTED** [review]
See above

**Comment by RDIL** [comment]
I think we have a scan for groups hook?

File: components/menus/destinations.ts (hunk 2 above)
Comment (AnthonyFuller) [reply components/menus/destinations.ts:422]: No arguments from me.

File: components/controller.ts (hunk 1 above)
Comment (AnthonyFuller) [reply components/controller.ts:640]: Doh! I forgot to do this.

**Comment by AnthonyFuller** [comment]
> I think we have a scan for groups hook?

We do, but it is named `getContractIdsForGroupDiscovery`. Is it worth moving over to this?

File: components/contracts/missionsInLocation.ts [hunk 3]
```diff
@@ -16,310 +16,634 @@
...
-            "fe088a10-5dbf-460f-bbe2-6b55e7a66253",
-        ],
-        LOCATION_NORTHSEA: [
-            "e63eeb62-29ef-428d-b003-ea043b1f11f9",
-            "b66f151d-47a7-4681-a403-c48a46916224",
-            "dbb0e22d-084b-4b57-8616-42290982fd90",
-            "4fbfae2e-a5e7-4b79-b008-94f6cbcb13cb",
-            "3721e543-b5e6-4af8-a4fc-c92e9a4453bd",
-            "8c6daf5e-5974-4438-af20-71ff570c7ff3",
+export const missionsInLocation = {
```
Comment (RDIL) [inline components/contracts/missionsInLocation.ts:26]: Explicitly type this object

File: components/controller.ts [hunk 4]
```diff
@@ -626,6 +630,50 @@ export class Controller {
...
+    /**
+     * Fixes a contract based on game version.
+     *
+     * An example of this is the location for Holiday Hoarders changing in
+     * HITMAN 3 thus breaking the contract in standalone 2016.
+     *
+     * @param contract The contract to fix.
+     * @param gameVersion The game version.
+     * @returns The fixed contract.
+     * @private
```
Comment (RDIL) [inline components/controller.ts:642]:
```suggestion
```
Unneeded due to the TS modifier

**Review by RDIL — APPROVED** [review]
LGTM % ^

File: components/controller.ts (hunk 4 above)
Comment (AnthonyFuller) [reply components/controller.ts:642]: Webstorm added it :+1:

File: components/contracts/missionsInLocation.ts (hunk 3 above)
Comment (AnthonyFuller) [reply components/contracts/missionsInLocation.ts:26]: Does [this](https://github.com/thepeacockproject/Peacock/pull/550/files#diff-b388de6427dba20db03a608266dd354bb8fb9769041dc9c43d5810e63d75920aR649) not _satisfy_ that?

**Comment by AnthonyFuller** [comment]
Sorry @ Private for that tag. Didn't even expect that.

What about `controller.addEscalation`?
